/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"


void
factprog_1(char *host,int a)
{
	CLIENT *clnt;
	int  *result_1;
	myStruct  factproc_fact_1_arg;
	factproc_fact_1_arg.a=a;

#ifndef	DEBUG
	clnt = clnt_create (host, FACTPROG, FACTVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = factproc_fact_1(&factproc_fact_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("\nFactorial of %d = %d\n",a,*result_1);

	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int b;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	printf("Enter value of a:");
	scanf("%d",&b);
	host = argv[1];
	factprog_1 (host,b);
exit (0);
}
