/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
factproc_fact_1_svc(myStruct *argp, struct svc_req *rqstp)
{
	static int  result;
	int i,factorial = 1;
	/*
	 * insert server code here
	 */
	if (argp->a < 0)
        factorial = -1;

    	else
    	{
		for(i=1; i<=argp->a; ++i)
		{
		    factorial *= i;      
		}
        }


	result = factorial;
	return &result;
}
